# Generated by Django 4.2.29 on 2026-09-26 17:03

from django.db import migrations, models
from django.db.models import Count
import django.db.models.functions.text


def check_existing_emails(apps, schema_editor):
    # Fail with the offending users listed, instead of a bare constraint error.
    CustomUser = apps.get_model('users', 'CustomUser')
    empty = list(CustomUser.objects.filter(email='').values_list('id', 'username'))
    duplicates = list(
        CustomUser.objects.annotate(lower_email=django.db.models.functions.text.Lower('email'))
        .values('lower_email')
        .annotate(n=Count('id'))
        .filter(n__gt=1)
        .values_list('lower_email', flat=True)
    )
    problems = []
    if empty:
        problems.append(f'users with an empty email (id, username): {empty}')
    for email in duplicates:
        users = list(
            CustomUser.objects.filter(email__iexact=email).values_list('id', 'username')
        )
        problems.append(f'email {email!r} is shared by (id, username): {users}')
    if problems:
        raise RuntimeError(
            'Fix these users before migrating, e.g. in the Django admin:\n'
            + '\n'.join(problems)
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_first_name'),
    ]

    operations = [
        migrations.RunPython(check_existing_emails, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='users_customuser_email_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(check=models.Q(('email', ''), _negated=True), name='users_customuser_email_not_empty'),
        ),
    ]
