# Generated by Django 5.2.17 on 2026-10-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
