version: '3.7'

services:
  web:
    env_file:
      - .env
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000 --settings=project.settings.development
    # gunicorn project.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  redis:
    image: redis:alpine
    ports:
    - 6379:6379
  celery:
    env_file: .env
    build: .
    command: celery -A project worker -l DEBUG
    volumes:
      - .:/code
    depends_on:
      - redis
  celery-beat:
    env_file: .env
    build: .
    command: celery -A project beat -l INFO
    volumes:
      - .:/code
    depends_on:
      - redis
volumes:
  postgres_data: