version: '3.7'

services:
  web:
    env_file:
      - .env
    build: .
    command: gunicorn project.wsgi -b 0.0.0.0:8000
    # In publicly hosted production use gunicorn
    # command:  python /code/manage.py runserver 0.0.0.0:8000 --settings=project.settings.production
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
volumes:
  postgres_data: