databases:
  - name: forum-app-postgres
    databaseName: forum_app_postgres
    user: forum_app_postgres_user

services:
  - type: web
    name: mysite
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: forum-app-postgres
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: CELERY_BROKER_URL
        fromDatabase:
          name: forum-app-redis
          type: redis
          property: connectionString
  - type: redis
    name: forum-app-redis
    region: ohio
#    env: python
#    envVars:
#      - key: REDIS_URL
#        fromService:
#          name: forum-app-redis
#          type: redis
#          property: connectionString
  - type: worker
    name: queue
    region: ohio
    env: python
    # buildCommand: "pip install -r requirements.txt"
    startCommand: "celery --app tasks worker --loglevel info --concurrency 4"
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: forum-app-redis
          type: redis
          property: connectionString

#  - type: redis
#      name: private redis
#      ipAllowList: [ ]