# Generated by Django 5.2.17 on 2026-10-03 17:33

from django.conf import settings
from django.db import migrations, models


def create_site_settings(apps, schema_editor):
    SiteSettings = apps.get_model('pages', 'SiteSettings')
    Site = apps.get_model('sites', 'Site')
    site_settings, _ = SiteSettings.objects.get_or_create(pk=1)
    # Sites' display name follows the title (SiteSettings.save). Django creates the
    # example.com record only after all migrations, so on a new database create it here.
    site, created = Site.objects.get_or_create(
        pk=settings.SITE_ID, defaults={'domain': 'example.com', 'name': site_settings.title}
    )
    if not created:
        Site.objects.filter(pk=site.pk).update(name=site_settings.title)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Wildvasa', help_text="The site's name: header, tab, emails and authenticator apps.", max_length=60)),
                ('tagline', models.CharField(default='A private forum. Sign in to read and write.', help_text="Under the name on the visitors' home page.", max_length=200)),
                ('invitation_note', models.CharField(default='Membership is by invitation. Got an invitation? Use the link in the email.', help_text="On the visitors' home page while signup is closed.", max_length=300)),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
        migrations.RunPython(create_site_settings, migrations.RunPython.noop),
    ]
