# Generated by Django 5.2.17 on 2026-10-03 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_site_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='latest_threads',
            field=models.PositiveSmallIntegerField(default=15, help_text='Threads on the Latest page (5 to 50).', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='posts_per_page',
            field=models.PositiveSmallIntegerField(default=25, help_text='Posts per page of a thread (5 to 100). Old links to a page may then lead elsewhere.', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='recent_threads',
            field=models.PositiveSmallIntegerField(default=3, help_text='Threads under Recent activity, above the forum list (1 to 10).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='threads_per_page',
            field=models.PositiveSmallIntegerField(default=20, help_text='Threads per page of a forum (5 to 100). Old links to a page may then lead elsewhere.', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
