# Generated by Django 5.2.17 on 2026-10-08 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_site_settings_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='notification_mail_delay',
            field=models.PositiveSmallIntegerField(default=5, help_text="Minutes a reply waits before it is mailed to the thread's subscribers. Those who open the thread in that time get no mail (0 to 30; 0 mails at once).", validators=[django.core.validators.MaxValueValidator(30)]),
        ),
    ]
