# Generated by Django 2.2.5 on 2019-10-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='text',
            field=models.TextField(default='<empy>'),
        ),
    ]
