# Generated by Django 2.2.5 on 2019-10-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_thread_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
