# Generated by Django 2.2.5 on 2019-12-03 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('forums', '0006_auto_20191203_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts',
                                    to='forums.Thread'),
        ),
    ]
