# Generated by Django 3.0.3 on 2020-03-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0012_auto_20200112_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='text',
            field=models.TextField(),  # was martor.models.MartorField, a TextField subclass
        ),
    ]
