# Generated by Django 3.0.3 on 2020-03-24 12:34

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0013_auto_20200324_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=martor.models.MartorField(),
        ),
    ]
