# Generated by Django 5.2.17 on 2026-10-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0018_text_size_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='announcement',
            field=models.BooleanField(default=False, help_text='Keep this thread at the top of its forum, above the others.'),
        ),
    ]
