# Generated by Django 5.2.17 on 2026-10-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0020_search_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='posting',
            field=models.CharField(choices=[('open', 'Open: every member can start threads and reply'), ('moderators_start', 'Moderators start threads; members can reply'), ('moderators_only', 'Moderators only: members can read')], default='open', help_text='Closing a forum stops new threads or replies. What is already there stays.', max_length=20, verbose_name='Who can post'),
        ),
    ]
