# Generated by Django 5.2.17 on 2026-10-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0023_edited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='description',
            field=models.CharField(max_length=500, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='You can use Markdown: **bold**, *italic*, `code`, > quote, lists, links and tables.', max_length=20000, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='announcement',
            field=models.BooleanField(default=False, help_text='Keep this thread at the top of its forum, above the others.', verbose_name='announcement'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='text',
            field=models.TextField(help_text='You can use Markdown: **bold**, *italic*, `code`, > quote, lists, links and tables.', max_length=20000, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(max_length=300, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.TextField(choices=[('N', 'NotProvided'), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='N', max_length=1, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='github_url',
            field=models.URLField(blank=True, verbose_name='github url'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=50, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='signature',
            field=models.TextField(blank=True, max_length=500, verbose_name='signature'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='web_site',
            field=models.URLField(blank=True, verbose_name='web site'),
        ),
    ]
